#!/usr/bin/env python3
"""Plan and apply frontmatter metadata migrations for selected vault notes."""

from __future__ import annotations

import argparse
import datetime as dt
import importlib.util
import json
import sys
from dataclasses import dataclass
from pathlib import Path


TOOLKIT_DIR = Path(__file__).resolve().parent
DEFAULT_REPORT = Path("08_SYSTEMS/Engineering Toolkit/Reports/Metadata Migration Preview.md")
DEFAULT_ROLLBACK = Path("08_SYSTEMS/Engineering Toolkit/Reports/metadata_migration_rollback.json")


def load_vault_validator():
    spec = importlib.util.spec_from_file_location("vault_validator", TOOLKIT_DIR / "vault_validator.py")
    if spec is None or spec.loader is None:
        raise RuntimeError("Unable to load vault_validator.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


vault_validator = load_vault_validator()


@dataclass(frozen=True)
class ProposedChange:
    path: str
    field: str
    old_value: object | None
    new_value: object


def yaml_value(value: object) -> str:
    if isinstance(value, list):
        if not value:
            return "[]"
        return "[" + ", ".join(json.dumps(str(item), ensure_ascii=False) for item in value) + "]"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    return json.dumps(value, ensure_ascii=False)


def render_frontmatter(data: dict[str, object], body: str) -> str:
    lines = ["---"]
    for key, value in data.items():
        lines.append(f"{key}: {yaml_value(value)}")
    lines.extend(["---", body.lstrip("\n")])
    return "\n".join(lines)


def selected_notes(root: Path, paths: list[str], include_hidden: bool) -> list:
    notes_by_path = {note.relative_path: note for note in vault_validator.load_notes(root, include_hidden)}
    selected = []
    for raw in paths:
        rel = Path(raw).as_posix()
        note = notes_by_path.get(rel)
        if note is None:
            raise SystemExit(f"error: target note not found or not scanned: {rel}")
        selected.append(note)
    return selected


def proposed_defaults(args: argparse.Namespace) -> dict[str, object]:
    defaults: dict[str, object] = {}
    mapping = {
        "artifact_type": args.artifact_type,
        "institutional_owner": args.institutional_owner,
        "cognitive_function": args.cognitive_function,
        "reasoning_engine": args.reasoning_engine,
        "status": args.status,
        "version": args.version,
    }
    for key, value in mapping.items():
        if value is not None:
            defaults[key] = value
    for key in ["dependencies", "related_documents", "related_research_programs", "aliases", "tags", "authors"]:
        if key in vault_validator.REQUIRED_FIELDS:
            defaults.setdefault(key, [])
    today = dt.date.today().isoformat()
    defaults.setdefault("created", today)
    defaults.setdefault("updated", today)
    return defaults


def plan_changes(notes: list, defaults: dict[str, object], fill_required: bool) -> list[ProposedChange]:
    changes: list[ProposedChange] = []
    required = vault_validator.REQUIRED_FIELDS if fill_required else set(defaults)
    for note in notes:
        if not note.has_frontmatter:
            continue
        for field in sorted(required):
            if field in note.frontmatter:
                continue
            value = defaults.get(field)
            if value is None:
                if field in vault_validator.LIST_FIELDS:
                    value = []
                else:
                    continue
            changes.append(ProposedChange(note.relative_path, field, None, value))
    return changes


def render_report(root: Path, changes: list[ProposedChange], applied: bool) -> str:
    today = dt.date.today().isoformat()
    now = dt.datetime.now().astimezone().isoformat(timespec="seconds")
    lines = [
        "---",
        'title: "Metadata Migration Preview"',
        "aliases: []",
        "tags: [systems, engineering, metadata, migration, report, alpha-proxima]",
        f"created: {today}",
        f"updated: {today}",
        "status: draft",
        'version: "1.0.0"',
        'authors: ["CODEX"]',
        "artifact_type: engineering-report",
        'institutional_owner: "Alpha Proxima Foundation"',
        'cognitive_function: "Implementation"',
        'reasoning_engine: "CODEX"',
        'dependencies: ["[[Tool 003 - Metadata Migration Utility]]"]',
        'related_documents: ["[[Alpha Proxima Engineering Toolkit]]"]',
        "related_research_programs: []",
        "---",
        "",
        "# Metadata Migration Preview",
        "",
        "## Purpose",
        "",
        "Preview or record metadata migration changes generated by [[Tool 003 - Metadata Migration Utility]].",
        "",
        "## Summary",
        "",
        f"- Vault: `{root}`",
        f"- Generated: `{now}`",
        f"- Applied: `{str(applied).lower()}`",
        f"- Proposed changes: `{len(changes)}`",
        "",
        "## Changes",
        "",
        "| Path | Field | Old Value | New Value |",
        "|------|-------|-----------|-----------|",
    ]
    for change in changes:
        old_value = "" if change.old_value is None else str(change.old_value).replace("|", "\\|")
        new_value = str(change.new_value).replace("|", "\\|")
        lines.append(f"| `{change.path}` | `{change.field}` | {old_value} | {new_value} |")
    lines.extend(
        [
            "",
            "## Implementation Notes",
            "",
            "This utility changes only explicitly selected notes. It does not infer institutional judgment.",
            "",
            "## Future Improvements",
            "",
            "- [ ] Add policy files for repeatable migration profiles.",
            "- [ ] Add richer rollback metadata.",
            "",
            "## Version History",
            "",
            "| Version | Date | Author | Summary |",
            "|---------|------|--------|---------|",
            f"| 1.0.0 | {today} | [[CODEX]] | Metadata migration report generated |",
        ]
    )
    return "\n".join(lines) + "\n"


def apply_changes(root: Path, notes: list, changes: list[ProposedChange], rollback_path: Path) -> None:
    rollback = {
        "created": dt.datetime.now().astimezone().isoformat(timespec="seconds"),
        "files": {},
    }
    by_path: dict[str, list[ProposedChange]] = {}
    for change in changes:
        by_path.setdefault(change.path, []).append(change)
    for note in notes:
        note_changes = by_path.get(note.relative_path)
        if not note_changes:
            continue
        rollback["files"][note.relative_path] = note.text
        data = dict(note.frontmatter)
        for change in note_changes:
            data[change.field] = change.new_value
        note.path.write_text(render_frontmatter(data, note.body), encoding="utf-8")
    rollback_path.parent.mkdir(parents=True, exist_ok=True)
    rollback_path.write_text(json.dumps(rollback, indent=2, ensure_ascii=False), encoding="utf-8")


def restore_rollback(root: Path, rollback_file: Path) -> int:
    data = json.loads(rollback_file.read_text(encoding="utf-8"))
    files = data.get("files", {})
    for rel, text in files.items():
        path = root / rel
        path.write_text(text, encoding="utf-8")
    print(f"Restored {len(files)} files from rollback: {rollback_file}")
    return 0


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--vault", default=".", help="Vault root. Defaults to current working directory.")
    parser.add_argument("--paths", nargs="*", default=[], help="Explicit Markdown note paths to migrate.")
    parser.add_argument("--paths-file", help="Text file containing one target path per line.")
    parser.add_argument("--output", default=str(DEFAULT_REPORT), help="Preview/progress report path.")
    parser.add_argument("--rollback-file", default=str(DEFAULT_ROLLBACK), help="Rollback JSON path.")
    parser.add_argument("--restore-rollback", help="Restore files from a rollback JSON file.")
    parser.add_argument("--include-hidden", action="store_true", help="Include hidden/tool-managed folders.")
    parser.add_argument("--apply", action="store_true", help="Apply changes. Default is dry run.")
    parser.add_argument("--batch", action="store_true", help="Batch mode; requires --yes with --apply.")
    parser.add_argument("--yes", action="store_true", help="Confirm apply without interactive prompt.")
    parser.add_argument("--fill-required", action="store_true", help="Fill missing required fields where defaults are known.")
    parser.add_argument("--artifact-type")
    parser.add_argument("--institutional-owner")
    parser.add_argument("--cognitive-function")
    parser.add_argument("--reasoning-engine")
    parser.add_argument("--status")
    parser.add_argument("--version")
    parser.add_argument("--force", action="store_true", help="Overwrite output report.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    root = Path(args.vault).expanduser().resolve()
    if args.restore_rollback:
        return restore_rollback(root, Path(args.restore_rollback).expanduser().resolve())

    paths = list(args.paths)
    if args.paths_file:
        paths.extend(line.strip() for line in Path(args.paths_file).read_text(encoding="utf-8").splitlines() if line.strip())
    if not paths:
        print("error: provide --paths or --paths-file; metadata migration never scans targets implicitly", file=sys.stderr)
        return 2
    if args.apply and args.batch and not args.yes:
        print("error: batch apply requires --yes", file=sys.stderr)
        return 2

    notes = selected_notes(root, paths, args.include_hidden)
    changes = plan_changes(notes, proposed_defaults(args), args.fill_required)
    output = Path(args.output).expanduser()
    if not output.is_absolute():
        output = root / output
    if output.exists() and not args.force:
        print(f"error: refusing to overwrite existing report: {output}", file=sys.stderr)
        return 4
    output.parent.mkdir(parents=True, exist_ok=True)

    applied = False
    if args.apply and changes:
        if not args.yes:
            answer = input(f"Apply {len(changes)} metadata changes? Type YES to continue: ")
            if answer != "YES":
                print("Migration cancelled.")
                output.write_text(render_report(root, changes, False), encoding="utf-8")
                return 0
        rollback = Path(args.rollback_file).expanduser()
        if not rollback.is_absolute():
            rollback = root / rollback
        apply_changes(root, notes, changes, rollback)
        applied = True
        print(f"Rollback written: {rollback}")

    output.write_text(render_report(root, changes, applied), encoding="utf-8")
    print(f"Report written: {output}")
    print(f"Changes: {len(changes)} proposed; applied={applied}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
