import {useState} from 'react'
const key='alpha-proxima.department-shortcuts.v1'
function load(){try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return {}}}
export default function DepartmentWorkspace({system,nodes,onClose,onOpenNote,onOpenCenter}){
 const [tab,setTab]=useState('Dossiers'),[links,setLinks]=useState(load),[name,setName]=useState(''),[url,setUrl]=useState(''),[kind,setKind]=useState('Outil'),[error,setError]=useState('')
 const rows=links[system.id]||[]
 function save(e){e.preventDefault();setError('');let parsed;try{parsed=new URL(url);if(!['https:','http:'].includes(parsed.protocol)||parsed.username||parsed.password)throw Error()}catch{setError('Utilise une adresse web http ou https, sans identifiant ni mot de passe.');return}if(!name.trim())return;const next={...links,[system.id]:[...rows,{id:Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join(''),name:name.trim(),url:parsed.href,kind}]};try{localStorage.setItem(key,JSON.stringify(next));setLinks(next);setName('');setUrl('')}catch{setError('Impossible d’enregistrer ce raccourci dans ce navigateur.')}}
 function remove(id){const next={...links,[system.id]:rows.filter(r=>r.id!==id)};try{localStorage.setItem(key,JSON.stringify(next));setLinks(next)}catch{setError('Enregistrement indisponible.')}}
 return <section className="department-workspace" role="dialog" aria-modal="true" aria-label={'Atelier '+system.name} style={{'--center-color':'#'+system.color.toString(16).padStart(6,'0')}} onKeyDown={e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const items=[...e.currentTarget.querySelectorAll('button:not(:disabled),a[href],input,select')].filter(n=>n.offsetParent!==null);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}}>
  <header className="workspace-header"><div><small>UNIVERS / {system.center.toUpperCase()} / ATELIER</small><h1>{system.name}</h1><p>{system.detail}</p></div><button autoFocus onClick={onClose}>Retour au corps</button></header>
  <nav className="workspace-tabs" aria-label="Sections de l’atelier">{['Dossiers','Équipe et outils'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
  {tab==='Dossiers'?<div className="workspace-content"><h2>Le travail de ce département</h2><p>Objectifs et documents explicitement attribués à {system.name} dans ta mémoire.</p>
   {(system.objectives.length||nodes.length)?<div className="workspace-documents">{[...new Map([...system.objectives,...nodes].map(n=>[n.path||n.id||n.title,n])).values()].map((n,i)=><button disabled={!n.path} key={n.path||n.id||i} onClick={()=>onOpenNote(n.path,n.title)}><strong>{n.title}</strong><span>{n.status||n.nodeType||'Document'}{n.path?' · Ouvrir la source':' · Signal sans document source'}</span></button>)}</div>:<div className="workspace-empty"><h3>Aucun dossier attribué pour l’instant</h3><p>Ouvre la mémoire du département pour retrouver ses documents. Les notes sans responsable restent dans la mémoire commune.</p></div>}
   <button className="workspace-primary" onClick={()=>onOpenCenter(system.name)}>Ouvrir la mémoire de {system.name}</button>
  </div>:<div className="workspace-content"><h2>Ton équipe et tes outils</h2><p>Garde ici les liens utiles à ce département : espace d’un collègue, conversation avec un agent ou outil de travail.</p>
   <div className="workspace-connections">{rows.map(r=><div key={r.id}><a href={r.url} target="_blank" rel="noopener noreferrer"><small>{r.kind}</small><strong>{r.name}</strong><span>Ouvrir</span></a><button aria-label={'Retirer '+r.name} onClick={()=>remove(r.id)}>Retirer</button></div>)}</div>
   {!rows.length&&<p className="workspace-empty">Aucun espace associé à ce centre.</p>}
   <form onSubmit={save} className="workspace-connect"><h3>Associer un espace</h3><label>Type<select value={kind} onChange={e=>setKind(e.target.value)}><option>Outil</option><option>Collègue</option><option>Agent</option></select></label><label>Nom<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="Ex. Atelier de recherche"/></label><label>Adresse de l’espace<input required type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label><button className="workspace-primary">Ajouter le raccourci</button>{error&&<p role="alert">{error}</p>}<small>Ces raccourcis restent dans ce navigateur. Ajouter un lien n’invite personne et n’accorde aucun accès à tes données.</small></form>
  </div>}
 </section>
}
