export const baseSystems = [
  { id:'LUMIAION', name:'LUMIAION', center:'Crown', chakra:'Vision', color:0xb85cff, anchor:[.617,.109], detail:'Consciousness, governance, orchestration and synthesis.', invitation:'See the whole system and choose what deserves attention.', facets:['Founder attention','Council synthesis','System coherence'] },
  { id:'SOHMA', name:'SOHMA', center:'Third Eye', chakra:'Intelligence', color:0x5145cd, anchor:[.634,.168], detail:'Consciousness, meaning, symbols and human alignment.', invitation:'Enter the field of meaning, reflection and inner alignment.', facets:['Meaning','Symbols','Consciousness'] },
  { id:'JERANIUM', name:'JERANIUM', center:'Throat', chakra:'Routing', color:0x279eff, anchor:[.622,.307], detail:'Knowledge, research, evidence and institutional intelligence.', invitation:'Route evidence into language the institution can use.', facets:['Research','Knowledge routing','Evidence'] },
  { id:'ANAHATA', name:'ANAHATA', center:'Heart', chakra:'Relationships', color:0x36da78, anchor:[.631,.400], detail:'The relational field: people, care, trust and coherence.', invitation:'Hold the people, relationships and care around the work.', facets:['People','Care','Trust'] },
  { id:'VORTEX', name:'VORTEX', center:'Solar Plexus', chakra:'Execution', color:0xffdd28, anchor:[.632,.510], detail:'Finance, strategy, markets and economic direction.', invitation:'Transform direction into strategy, movement and economic clarity.', facets:['Finance','Strategy','Markets'] },
  { id:'CREATION', name:'CREATION', center:'Sacral', chakra:'Creation', color:0xff8a22, anchor:[.632,.605], detail:'Ideas, making, experiments and generative momentum.', invitation:'Give emerging ideas a place to become real.', facets:['Ideas','Making','Experiments'] },
  { id:'ATHENA', name:'ATHENA', center:'Root', chakra:'Stability', color:0xf02d45, anchor:[.634,.698], detail:'Health, body, performance and material wellbeing.', invitation:'Ground the system in body, health and sustainable performance.', facets:['Health','Performance','Stability'] },
]
